build:
	 clang++ \
	 -o index.out index.cpp \
	 -I/opt/homebrew/Cellar/glfw/3.3.8/include \
	 -framework CoreFoundation \
	 -framework OpenGL \
	 -L/opt/homebrew/Cellar/glfw/3.3.8/lib \
	 -lglfw
	 ./index.out